### ISSUE TITLE
local_genomes

### ISSUE THREAD

**Issue by TheSallyGardens** [nf-core/raredisease#124]
### Description of feature

Hi
How does it get the file under the local_genomes path？

**Comment by projectoriented** [comment]
Hello 👋 ! It depends which file but you can execute it like so:  
```shell
nextflow run . -profile hasta,dev_prio
 --genome GRCh38 
--input ../samplesheet_justhusky.csv 
--local_genomes ../references/ 
--igenomes_ignore
```

**Comment by projectoriented** [comment]
I hope this answered your question & you can see in the nextflow schema for more information. Closing this comment now 👋
