### ISSUE TITLE
Update resource request in usage.md

### ISSUE THREAD

**Issue by jemten** [nf-core/raredisease#137]
The resource documentation is extensively referring to the RNA seq pipeline. While it is a good pipeline it would be nice to use nf-core/raredisease examples instead

**Comment by ramprasadn** [comment]
Is this still relevant @jemten? Template has since been changed to point to [nf-core website](https://nf-co.re/docs/usage/configuration#max-resources) 😄

**Comment by jemten** [comment]
let's close this
