### ISSUE TITLE
VEP 

### ISSUE THREAD

**Issue by jemten** [nf-core/raredisease#14]
## Is your feature request related to a problem? Please describe

Add VEP from nf-core modules

**Comment by jemten** [comment]
Hi there @sysbiocoder,
Noticed that you closed the issue. I reopened it and assigned you to it since you spoke about adding VEP during the meeting. Feel free to remove yourself from the issue if there are other issues that you'd rather work on.

**Comment by sysbiocoder** [comment]
Sorry I was browsing through the pages and somehow without my knowledge I closed. I am happy to work on it.  As I understood we have VEP already present in Sarek pipeline, we need to add it here. Please let me know if I have understood right.

**Comment by jemten** [comment]
No worries at all. Indeed, sarek runs VEP but we need to add it to this pipeline as well. However, before we can add vep we must produce a vcf :)

**Comment by sysbiocoder** [comment]
So do we need to start with fastq and subsequent tools to produce vcf

**Comment by henrikstranneheim** [comment]
Yes, it is nice to always be able to have a fully operational pipeline for all "steps" prior to the one you are developing. It makes it a lot easier to test and see if you broke anything and also does not leave code in the repositiory that is not used anywhere (yet) and risk going stale

**Comment by sysbiocoder** [comment]
ok, thank you for explaining clearly.

**Comment by jemten** [comment]
done in #200
