### ISSUE TITLE
Make a "metromap" for the pipeline

### ISSUE THREAD

**Issue by Gwennid** [nf-core/raredisease#147]
### Description of feature

To complement the schematic overview in issue #145, we could have a "metromap" like in several other nf-core pipelines. This could be a way to show the different ways to run the pipeline, e.g. use the Sentieon subworkflow, use the annotation etc. These plots tend to get crowded and hard to read, one could have the complete plot on top and under it show the different options (highlighting the different "itineraries").
Inspiration: [eager](https://github.com/nf-core/eager/blob/master/docs/images/usage/eager2_metromap_complex.svg), [cutandrun](https://raw.githubusercontent.com/nf-core/cutandrun/a1389df5cdd18cb32925faacf3e53325b9f06bb8/docs/images/cutandrun-flow-diagram-v1-0_2.png).

**Comment by jemten** [comment]
done in #432
