### ISSUE TITLE
Add check for case_id

### ISSUE THREAD

**Issue by jemten** [nf-core/raredisease#185]
### Description of feature

When going from sample vcfs to a case vcf the "case_id" info is required in order to generate an outfile with a sensible name (not ".bcf"). 

We should add a check for that information when generating the case channel

**Comment by EmmaCAndersson** [comment]
Added PR in ClinicalGenomicsGBG fork (https://github.com/ClinicalGenomicsGBG/nf-core-raredisease/tree/check_case_id)

**Comment by ramprasadn** [comment]
This issue was first fixed in https://github.com/nf-core/raredisease/pull/357, and the logic was later updated in https://github.com/nf-core/raredisease/pull/386
