### ISSUE TITLE
GATK4 nf-core containers lacking package (gcnvkernel) required for the gcnvcaller

### ISSUE THREAD

**Issue by ryanjameskennedy** [nf-core/raredisease#189]
### Description of the bug
**Major issue ([link to issue report](https://github.com/broadinstitute/gatk/issues/8097)):** 
I'm getting the following error when running an nf-core module test:
```
TypeError: ('The following error happened while compiling the node', forall_inplace,cpu,scan_fn}(Elemwise{Maximum}[(0, 0)].0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, IncSubtensor{InplaceSet;:int64:}.0, Elemwise{mul,no_inplace}.0, Subtensor{int64::}.0, Elemwise{sub,no_inplace}.0), '\n', "Inconsistency in the inner graph of scan 'scan_fn' : an input and an output are associated with the same recurrent state and should have the same type but have type 'TensorType(float64, row)' and 'TensorType(float64, matrix)' respectively.")
```
I am using test files, which are obviously smaller as for short testing times i.e. the provided bam file only provides mapped reads for a small section of the genome.

**Conda & Singularity related issue:**
When trying to test modules from GATK4's germline CNV caller pipeline, modules that require a specific package (gcnvkernel) to cannot be tested using nf-core's containers. I have tried adding it to the bioconda-recipe (bioconda/bioconda-recipes#35164) but this has not worked. However if I use broadinstitute’s gatk container, it works perfectly. 

### Command used and terminal output

```console
(nf-core) $ nf-core modules create-test-yml
...
ModuleNotFoundError: No module named 'gcnvkernel'
...
```

### System information

Nextflow version 22.04.0.5697
Hardware: HPC
Executor: slurm
Container engine(s): Docker and Singularity
OS: Ubuntu 16.04.2 LTS
Version of nf-core/raredisease:

**Comment by ramprasadn** [comment]
Closing this issue since we are now using GATK container from Broad (instead of using the one from bioconda) which works fine.
