### ISSUE TITLE
New modules required: Sentieon

### ISSUE THREAD

**Issue by Gwennid** [nf-core/raredisease#27]
Here is a list of Sentieon tools that are relevant for the pipeline and for which issues have been opened in https://github.com/nf-core/modules.

- [x] bwa mem https://github.com/nf-core/modules/issues/732
- [x] LocusCollector https://github.com/nf-core/modules/issues/733
- [x] Dedup https://github.com/nf-core/modules/issues/734
- [x] DNAscope assigned to @Gwennid https://github.com/nf-core/modules/issues/715
- [x] TNscope assigned to @Gwennid https://github.com/nf-core/modules/issues/731
- [x] DNAModelApply https://github.com/nf-core/modules/issues/735

Another tool that might be relevant but for which there is no open issue at the moment:
- [x] WgsMetricsAlgo

**Comment by Gwennid** [comment]
Hi @nf-core/modules-team @ewels 
@pbiology asked someone from Sentieon about providing a test license for nf-core and apparently that won't be possible - they'd rather have each individual/organisation ask them for a test license.
So perhaps we need a different strategy for Sentieon tools (and other non-open source softwares) so that they pass the tests and can be included as DSL2 modules?

**Comment by ewels** [comment]
I see a couple of options here:

* Convince Sentieon that this _is_ one individual / organisation and that this entity is doing testing on behalf of the nf-core community
     * We do a lot of stuff as KTH / NGI on behalf of nf-core in the same way - basically every time we spend any money
     * The licence key could be put into an GitHub organisation secret and used without anyone else knowing it.
* We don't have automated testing for Sentieon tools in nf-core, and rely on local tests + people reporting when stuff is broken.

Let me know if I can be of any help.

Phil

**Comment by Gwennid** [comment]
It seems unlikely that we will get a test license permanently even if we convince them that nf-core is an individual/organization. But perhaps we could develop the modules locally in organisations that have a Sentieon license, and when we are ready to push the modules, we could ask for a test license for nf-core and check that the modules pass the tests at least initially? And in the future do as you said and rely on local tests and bug reports.

**Comment by jemten** [comment]
Feels like we can close this now and open up separate issues for any missing modules. Feel free to reopen if you want to continue working/discussing in this issue
