### ISSUE TITLE
Collect qc report for multiqc

### ISSUE THREAD

**Issue by jemten** [nf-core/raredisease#298]
Find processes that produces qc reports that can be processed by multiqc, collect them to a channel that we send to multiqc.

**Comment by peterpru** [comment]
QC_BAM subworkflow outputs added in PR: https://github.com/nf-core/raredisease/pull/302

**Comment by peterpru** [comment]
@jemten, I think for now we are done adding it. Maybe we can have a tick mark in the PR template that says something along the lines of: "Add any compatible output to multiQC"?
