### ISSUE TITLE
Add test dataset to enable CI tests

### ISSUE THREAD

**Issue by henrikstranneheim** [nf-core/raredisease#3]
## Is your feature request related to a problem? Please describe

Add test dataset to enable CI tests. New branch need to be created in [nf-core/test-datasets](https://github.com/nf-core/test-datasets)

## Describe the solution you'd like

- [Reuse test dataset from Sarek or similiar](https://github.com/nf-core/test-datasets/blob/master/docs/USE_EXISTING_DATA.md).

**Comment by projectoriented** [comment]
I'm using the tiny/normal test dataset from Sarek which points to chr20- I think we need to discuss further (e.g. pedigree) our samplesheet input requirements when you come back from 🌴 .
