### ISSUE TITLE
KeyError: 'X' at Tiddit stage

### ISSUE THREAD

**Issue by hrydbeck** [nf-core/raredisease#378]
### Description of the bug

At the stage of Tiddit the error message "KeyError: 'X'" is given. Googeling another part of the error message "Converting SIF file to temporary sandbox..." indicates the error might be associated with Singularity. Tried to run with Docker instead and got the same error message. I also tried with two different genomes NA12877 an NA12878. 

Longer version of error msg below:

Command error:
  INFO:    Converting SIF file to temporary sandbox...
  [M::main_ropebwt2] inserted 71301846 symbols in 4.725 sec, 12.905 CPU sec
  [M::main_ropebwt2] constructed FM-index in 4.906 sec, 13.085 CPU sec
  [M::main_ropebwt2] symbol counts: ($, A, C, G, T, N) = (471044, 20304876, 15110525, 15110525, 20304876, 0)
  [M::main_ropebwt2] rld: (tot, $, A, C, G, T, N) = (71301846, 471044, 20304876, 15110525, 15110525, 20304876, 0)
  [M::main] Version: r187
  [M::main] CMD: ropebwt2 -dNCr 12877_tiddit/clips.fa
  [M::main] Real time: 5.210 sec; CPU: 13.362 sec
  [M::fm6_unitig] choose prime 123457
  [M::main] Version: r178
  [M::main] CMD: fermi2 assemble -t 1 -l 81 -
  [M::main] Real time: 54.849 sec; CPU: 49.669 sec
  LIBRARY STATISTICS
  	Pair orientation = Forward-Reverse
  	Average Read length = 150.26575474936982
  	Average insert size = 992.4905793403768
  	Stdev insert size = 4681.7813985210305
  	99.95 percentile insert size = 66860.0
  
  Collecting signals on contig: 21
  Collecting signals on contig: MT
  ('total', 1228.4005160331726)
  Writing signals to file
  extracted signals in:
  -1320.0913121700287
  calculated coverage in:
  0.4158134460449219
  Clip read assembly in:
  245.58833026885986
  Traceback (most recent call last):
    File "/usr/local/bin/tiddit", line 11, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.10/site-packages/tiddit/__main__.py", line 161, in main
      sv_clusters=tiddit_cluster.main(prefix,contigs,contig_length,samples,library["mp"],args.e,args.l,max_ins_len,args.min_contig,args.skip_assembly)
    File "tiddit/tiddit_cluster.pyx", line 112, in tiddit.tiddit_cluster.main
  KeyError: 'X'
  INFO:    Cleaning up image...

### Command used and terminal output

```console
nextflow run nf-core/raredisease -revision 1.0.0  \
 -profile singularity \
 -params-file ../raredisease/workflow/GRCh37_params.yaml \
 --input samplesheetNA12877.csv \
 --outdir out_NA12877 \
 --genome GRCh37 \
 --save_reference \
 --skip_snv_annotation \
 --skip_sv_annotation \
 --skip_mt_analysis \
 --max_time 12.day \
 --max_cpus 30 \
 --max_memory 128.GB \
 -resume
```

### Relevant files

[relevant_files_issuereport.zip](https://github.com/nf-core/raredisease/files/12076880/relevant_files_issuereport.zip)

### System information

Nextflow version: 22.10.6
Hardware: HPC
Executor: Local
Container engine: Singularity
OS: CentOS Linux
Version of nf-core/raredisease: v1.0.0

**Comment by asp8200** [comment]
@hrydbeck : Is the SV calling with tiddit that is giving problems? If so, then it might be worth trying to disable it. I think it could be done by adding
```
        ext.when = { false }
```
around here:
https://github.com/nf-core/raredisease/blob/fdfb4a7c169b4ff3a0c5e76f85420ae6e84ec6d9/conf/modules/call_sv_tiddit.config#L19

As far as I can tell, the raredisease-pipeline should still be doing SV calling with Manta. Perhaps @ramprasadn can confirm that?

**Comment by asp8200** [comment]
I've notified Jesper Eisfeldt about this tiddit-related issue. Perhaps he can shed some light on this issue.

**Comment by hrydbeck** [comment]
Thank you again asp82. I did the edit you suggested, but got the same error message. I am not sure how to know that I am using the local edited repository. I am now running on a downloaded version 1.0.0 and using the "nextflow run main.nf ...". I assume that should make sure that I am running the from the local edited version. In that case the suggested editing doesnt seem to disable Tiddit. Thanks for helping and reaching out to people who could have interest and skills in resolving the issue. I will be away for the next two weeks.

**Comment by asp8200** [comment]
@hrydbeck : I think Jesper Eisfeldt of Tiddit might be interested in obtaining a copy of some data with which to reproduce the above-mentioned "bug" (it might be more of a data issue).

**Comment by ramprasadn** [comment]
Should we move this issue to TIDDIT repo? What do you guys think?

**Comment by hrydbeck** [comment]
The problem was that I set the "fasta" parameters as it is set in "test one sample", just copied the entry.
When I removed the fasta entry below from my parameter yaml file the problem disappeared
fasta: 'https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/reference.fasta'
Thank you the help Jesper Eisfeldt.
