### ISSUE TITLE
Default memory allocations for bwa index step are too low for igenomes

### ISSUE THREAD

**Issue by lfearnley** [nf-core/raredisease#379]
### Description of the bug

bwa-mem2 index module is tagged with 'process_single'; and is allocated only 6GB of memory as a result. If you run nf-raredisease on iGenomes (e.g. with `--genome GRCh38`), it tries to index the genome and the pipeline will crash due to this step running out of memory.

BWA MEM2 requires ~84GB for indexing of GRCh38 - https://github.com/bwa-mem2/bwa-mem2/blob/master/README.md describes it as "# Indexing the reference sequence (Requires 28N GB memory where N is the size of the reference sequence)."

**Comment by ramprasadn** [comment]
@lfearnley the default configurations used in raredisease are written keeping the test profile(&dataset, which is tiny) in mind. You should override these values like @fa2k has done in his configs [here](https://github.com/fa2k/raredisease-configs/blob/main/medGenConfigs/process-overrides.conf) to get it to work on larger datasets.

**Comment by lfearnley** [comment]
@ramprasadn - yep, makes sense - might be worth adding to docs?

**Comment by ramprasadn** [comment]
Good point! Will do 👍🏻 
I will reopen this issue and add it to the next milestone so we don't forget to add this info to docs

**Comment by ramprasadn** [comment]
Fixed in https://github.com/nf-core/raredisease/pull/394
