### ISSUE TITLE
Documentation - variant_catalog is for Stranger, not ExpansionHunter

### ISSUE THREAD

**Issue by lfearnley** [nf-core/raredisease#380]
### Description of the bug

The documentation at https://nf-co.re/raredisease/1.0.0/parameters describes variant_catalog as:

"Used with ExpansionHunter and if no catalogue is passed, then a default will be used."

This doesn't seem to be correct; using an ExpansionHunter catalog causes the pipeline to crash because of the absence of the "NormalMax" key. 

variant_catalog should be Stranger's extended JSON specification as described [here](https://github.com/Clinical-Genomics/stranger/blob/master/stranger/resources/variant_catalog_grch37.json)?

**Comment by lfearnley** [comment]
Also to note - stranger requires JSON files to have a .json extension and will exit with an exception if this isn't the case.

**Comment by ramprasadn** [comment]
Fixed in https://github.com/nf-core/raredisease/pull/394
