### ISSUE TITLE
nf-validation makes it difficult to run without Internet access

### ISSUE THREAD

**Issue by fa2k** [nf-core/raredisease#387]
### Description of the bug

I'm unable to run the new version 1.1.0 pipeline without Internet access because it can't get the nf-validation plugin.

I have opened a question at the nextflow developers GIthub, because it should arguably be solved ih nextflow itself: https://github.com/nextflow-io/nextflow/discussions/4126

I'm opening a bug here in case something can be done from the pipeline or nf-core sides. Will keep looking for a solution. (I think nf-validation is cool, and hope to find a way to use it)

### Command used and terminal output

```console
bash-4.2$ /ess/p164/data/durable/raredisease/1.1.0/nextflow-23.06.0-edge-all run \
> /ess/p164/data/durable/raredisease/1.1.0/nf-core-raredisease-1.1.0/workflow \
> -c /ess/p164/data/durable/raredisease/1.1.0/medGenConfigs/process-overrides.conf \

[...custom configs and parameters...]

> -resume

N E X T F L O W  ~  version 23.06.0-edge
Launching `/ess/p164/data/durable/raredisease/1.1.0/nf-core-raredisease-1.1.0/workflow/main.nf` [hungry_volhard] DSL2 - revision: b28dcce5fb
WARN: Nextflow self-contained distribution allows only core plugins -- User config plugins will be ignored: nf-validation
ERROR ~ Cannot find latest version of nf-validation plugin

 -- Check script '/ess/p164/data/durable/raredisease/1.1.0/nf-core-raredisease-1.1.0/workflow/main.nf' at line: 60 or see '.nextflow.log' file for more details
```

**Comment by fa2k** [comment]
The solution is given in the question linked above. I suppose it's reasonable to expect this of users, but would it be helpful if I wrote some usage documentation about running offline? Otherwise, feel free to close it.

**Comment by ramprasadn** [comment]
I think updating the usage documentation about running it offline would be helpful @fa2k. Lets leave this issue open and add it to the next milestone.
