### ISSUE TITLE
CADD container image with dependencies included

### ISSUE THREAD

**Issue by fa2k** [nf-core/raredisease#407]
### Description of feature

Currently CADD has to create its internal conda environments, used in the snakemake pipeline, for each instance when a process is started. There are some good reason for bundling the dependencies in the container image instead (including my usual problem- running without Internet access).

As a possible solution, I've created a [Dockerfile](https://github.com/fa2k/raredisease-configs/blob/main/scripts/cadd_Dockerfile) based on a [documented](https://github.com/kircherlab/CADD-scripts#manual-installation) way of pre-creating the conda environments. I don't know where I could submit this dockerfile and if it's up to the necessary standards.

**Comment by fa2k** [comment]
Submitted issue to BioContainers: https://github.com/BioContainers/containers/issues/528

**Comment by fa2k** [comment]
Status update, still not ready. I've got the BioContainer merged for version 1.6 and 1.6.post1 of CADD-scripts. I realised that version 1.6 is crashing when the set of variants is empty at some point in the pipeline. This is very likely to occur in the raredisease pipeline. The container image exists for version 1.6.post1, but there's no conda package for that version, and there's no point in submitting a PR to nf-core/modules until we have a working 1.6.post1 in bioconda. So I'm trying to make a conda recipe for version 1.6.post1 of CADD-scripts.

**Comment by jemten** [comment]
Is that fixed in version 1.6.1? When we run cadd for indels it's very rare that we have zero variants. It might happen for WES and gene panels when you split the cadd process over different regions regions. We try to solve that by only splitting for WGS samples.

**Comment by fa2k** [comment]
Yes it's called 1.6.post1 in the git tag, so that's what I've gone with.

https://github.com/kircherlab/CADD-scripts/releases

Good that it works with WGS for you. I've had issues with CADD, but I haven't run this version on a wide variety of WGS samples (using .post1 version now). I think I have most trouble with CADD on MT.

**Comment by ramprasadn** [comment]
This issue can now be closed, right, @fa2k?

**Comment by fa2k** [comment]
Ah yes, sorry I forgot. It's solved by a new version of the module in nf-core. I am trying to get CADD 1.7 to work in the same way though, and I'm having a huge amount of trouble with that.
