### ISSUE TITLE
Fill in "0" for missing information in ped file

### ISSUE THREAD

**Issue by jemten** [nf-core/raredisease#410]
Genmod expects missing data in the pedigree file to be either `0` or `.`. Using `0` seems to be the [standard](https://gatk.broadinstitute.org/hc/en-us/articles/360035531972-PED-Pedigree-format). This can be solved by updating this function to set missing values to 0. 
https://github.com/nf-core/raredisease/blob/c371602095ff83064f51747fe90dfc405ca7a864/workflows/raredisease.nf#L576

**Comment by ramprasadn** [comment]
Fixed
