### ISSUE TITLE
nf-raredisease crashing on filter_vep

### ISSUE THREAD

**Issue by lfearnley** [nf-core/raredisease#413]
### Description of the bug

--vep_filters is not marked as required, but the absence of this file will crash the FILTER_VEP_SNV step which runs by default.

### Command used and terminal output

```console
Standard execution, without --vep_filters.
```

**Comment by ramprasadn** [comment]
Thanks for reporting this, @lfearnley. Will fix this bug soon 👍🏻

**Comment by ramprasadn** [comment]
Fixed in #416
