### ISSUE TITLE
Sample names - reserved characters?

### ISSUE THREAD

**Issue by lfearnley** [nf-core/raredisease#417]
### Description of the bug

Is the underscore character not allowed in sample names?

I'm encountering the following in PEDDY_CHECK:PEDDY in a sample sheet with underscores:

```
2023-08-24 11:40:52 sml-n23.hpc.wehi.edu.au peddy.cli[38] WARNING 3 samples in vcf not in ped:
  A36833,A34489,A36620
  
2023-08-24 11:40:52 sml-n23.hpc.wehi.edu.au peddy.cli[38] WARNING 3 samples in ped not in vcf:
  A34489_2,A36620_1,A36833_1

```

**Comment by ramprasadn** [comment]
I don't see anything weird with peddy in my local tests. Could you look at the headers in your vcf and the ped file and see if they look different? And, if possible, could you share your samplesheet and ped file?

**Comment by lfearnley** [comment]
I've re-run this without underscores in the sample names, and it seems to have fixed it. I'll close out for now as I'm still working through samples; if I find more with underscores, I'll reopen.
