### ISSUE TITLE
Add TIDDIT/cov module

### ISSUE THREAD

**Issue by projectoriented** [nf-core/raredisease#43]
Our in-house pipeline (MIP) uses this tool and we want to add this to the nextflow pipeline. It's not part of nf-core modules yet: https://github.com/nf-core/modules/issues/792.

Once the module is added to nf-core/modules, then it'll be added to subworkflow `qc_bam.nf`

**Comment by Gwennid** [comment]
Is it correct that the module for tiddit/cov exists now and thus the next step is to include it in the QC subworkflow? Are you working on this @jemten ?

**Comment by jemten** [comment]
You are correct 😄

**Comment by projectoriented** [comment]
putting this here because made specifically for this issue: https://github.com/nf-core/raredisease/pull/73

**Comment by projectoriented** [comment]
related: https://github.com/nf-core/raredisease/pull/76
