### ISSUE TITLE
SMN copy number caller crashes due to mismatched reference genome

### ISSUE THREAD

**Issue by Jakob37** [nf-core/raredisease#437]
### Description of the bug

When executing the full raredisease-pipeline, it crashes in the step `NFCORE_RAREDISEASE:RAREDISEASE:SMNCOPYNUMBERCALLER`. It complains about "chr5" being an invalid contig. The reference genome we use locally is named "1", "2" and so on.

Raising this on the raredisease-slack, it was mentioned that SMNcaller expects a very specific genome version, and that it is worth raising this issue here as an issue. Peter Pruisscher writes:

> Hi! Smncaller is a bit tricky in that it expects a very specific version of either genome version 37 or 38, and will complain when it is different. We personally dealt with that by using the genome version that smncaller expects, but it is a problem for future releases of e.g. the t2t genome.

I am unsure in my specific case whether my error is due to the version of the reference genome (we use Hg38) or just that we seem to have a different naming convention ("1", "2" rather than "chr1", "chr2").

### Command used and terminal output

```console
Error output:


Caused by:
  Process `NFCORE_RAREDISEASE:RAREDISEASE:SMNCOPYNUMBERCALLER (giab_full)` terminated with an error exit status (1)

Command executed:

  echo giab_sample_dedup.bam | tr ' ' '
  ' > manifest.txt
  smn_caller.py \
      --genome 38 \
      --manifest manifest.txt \
      --prefix giab_full \
      --outDir "out" \
      --threads 4

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RAREDISEASE:RAREDISEASE:SMNCOPYNUMBERCALLER":
      SMNCopyNumberCaller: 1.1.2
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:root:Processing sample giab_sample_dedup at 2023-10-20 20:11:07.028514
  Traceback (most recent call last):
    File "/usr/local/bin/smn_caller.py", line 298, in <module>
      main()
    File "/usr/local/bin/smn_caller.py", line 267, in main
      smn_call = smn_cn_caller(
    File "/usr/local/bin/smn_caller.py", line 110, in smn_cn_caller
      normalized_depth = get_normed_depth(
    File "/usr/local/bin/depth_calling/bin_count.py", line 40, in get_normed_depth
      counts_for_normalization, gc_for_normalization, region_type_cn, read_length = count_reads_and_prepare_for_normalization(
    File "/usr/local/bin/depth_calling/bin_count.py", line 188, in count_reads_and_prepare_for_normalization
      region_reads = get_read_count(bamfile, region)
    File "/usr/local/bin/depth_calling/bin_count.py", line 104, in get_read_count
      reads = bamfile.fetch(region[0], region[1], region[2])
    File "pysam/libcalignmentfile.pyx", line 1091, in pysam.libcalignmentfile.AlignmentFile.fetch
    File "pysam/libchtslib.pyx", line 685, in pysam.libchtslib.HTSFile.parse_region
  ValueError: invalid contig `chr5`
```
```


### Relevant files

_No response_

### System information

Nextflow version: 23.04.2
Hardware: Local HPC
Executor: SLURM
Container engine: Singularity
OS: CentOS Linux
Version of nf-core/raredisease: dev-branch, latest commit: ` 65bda6a147`

**Comment by jemten** [comment]
Hi @Jakob37, 
SMN copy number caller uses a bed files to specify the regions where the analysis is to be performed, https://github.com/Illumina/SMNCopyNumberCaller/blob/master/data/. For genome build 38 this is hardcoded to use the `chr` prefix. While hg19 and grch37 used different conventions for naming chromosomes it was my understanding that the "chr" prefix is the standard for genome build 38. Best place to solve this would be to update [smncopynumbercaller](https://github.com/Illumina/SMNCopyNumberCaller) to include a bed file for hg38 without the chr prefix. 

Maybe a start could be to confirm that this is indeed the issue by adding the chr prefix to the chromosome names in your bam files or realign to a reference with the prefix.

**Comment by Jakob37** [comment]
> Hi @Jakob37, SMN copy number caller uses a bed files to specify the regions where the analysis is to be performed, https://github.com/Illumina/SMNCopyNumberCaller/blob/master/data/. For genome build 38 this is hardcoded to use the `chr` prefix. While hg19 and grch37 used different conventions for naming chromosomes it was my understanding that the "chr" prefix is the standard for genome build 38. Best place to solve this would be to update [smncopynumbercaller](https://github.com/Illumina/SMNCopyNumberCaller) to include a bed file for hg38 without the chr prefix.
> 
> Maybe a start could be to confirm that this is indeed the issue by adding the chr prefix to the chromosome names in your bam files or realign to a reference with the prefix.

Hi @jemten ! Yes, that makes sense. I am unfamiliar with the naming conventions, might very well be that hg38 has chr-named as convention. I'll give it a go to rerun against a chr-named reference.

**Comment by Jakob37** [comment]
Following up here, the SMN caller did indeed run through without errors after renaming the contigs to chr-based naming.

Regarding the naming conventions. Looking at the Hg38 I found that the one provided by Ensembl used number-based contig names (i.e. no "chr"):

https://ftp.ensembl.org/pub/release-110/fasta/homo_sapiens/dna/

Others that I found used the chr-based contigs.

**Comment by jemten** [comment]
Maybe we could add an optional step to rename the chromosomes in the bam file prior to SMNcopynumber caller and then switch back once the caller has run. Here is an example of how this can be done using [samtools reheader](https://www.htslib.org/doc/samtools-reheader.html)
```
samtools reheader -c 'perl -pe "s/^(@SQ.*)(\tSN:)(\d+|X|Y|MT)(\s|\$)/\$1Chr\$2\$3/"' in.bam
```
Switching back to your chr convention should also be fairly straight forward. What do you think @Jakob37?

**Comment by Jakob37** [comment]
> Maybe we could add an optional step to rename the chromosomes in the bam file prior to SMNcopynumber caller and then switch back once the caller has run. Here is an example of how this can be done using [samtools reheader](https://www.htslib.org/doc/samtools-reheader.html)
> 
> ```
> samtools reheader -c 'perl -pe "s/^(@SQ.*)(\tSN:)(\d+|X|Y|MT)(\s|\$)/\$1Chr\$2\$3/"' in.bam
> ```
> 
> Switching back to your chr convention should also be fairly straight forward. What do you think @Jakob37?

I'll ask with the other people here in Lund whether it is OK for us to switch back to chr-named contigs.
