### ISSUE TITLE
Question on the use of Sentieon's Bwa-mem and regular Bwa-mem in the Mitochondria subworkflow and in general if applies.

### ISSUE THREAD

**Issue by vruano** [nf-core/raredisease#452]
I have noticed that the Mitochondria variant calling subworkflow aligns reads to the Mitochondria using the general bwamem2 modules as well as Sentieon's implentation of bwa mem. Then the both alignments are combined before calling variants. 

 [subworkflows/local/mitochondria/align_and_call_MT.nf](https://github.com/nf-core/raredisease/blob/master/subworkflows/local/mitochondria/align_and_call_MT.nf)

My understanding is that Sentieon's implementation offer faster wall-time but is supposed to return the same result so why is the gain in doing this re-alignment twice and merge?

**Comment by jemten** [comment]
Hello @vruano,
A few things here. You are correct that the sentieon and bwa alignment should give the same results. Actually we only use one of those depending on which aligner you have specified, you can see the code here, https://github.com/nf-core/raredisease/blob/c371602095ff83064f51747fe90dfc405ca7a864/conf/modules/align_and_call_MT.config#L21
The join that follows should only ever contain the results from one of the aligners. 

Then of course we actually do alignment twice with the chosen aligner, against the original MT sequence and once against the shifted sequence. Variant calling is then done on the two alignments and the variants are joined.

**Comment by vruano** [comment]
I see, is this a common nf-core or nextflow idiom? I found it a bit misleading I would rather see a if-else-if... else instead but perhaps is just me.

**Comment by jemten** [comment]
Yeah, some extra comments explaining this wouldn't hurt. It should say in the pipeline documentation that only one aligner is being used but it's not self evident by just looking at the subworkflow that that is the case. I believe that different nf-core pipelines have different ways of handling these kind of operations. 

@maxulysse, do you know if there is a consensus in the community on how to handle these operations?

**Comment by maxulysse** [comment]
Not really, I like the possibilities offered by the `ext.when`, but as it uncouples the underlying logic I try to use it as sparsely as possible and explain what is happening with comments.
Another good alternative would be using switch cases as in https://github.com/nf-core/modules/blob/master/subworkflows/nf-core/fastq_align_dna/main.nf

**Comment by ramprasadn** [comment]
This has been addressed in the dev branch so I am closing this issue.
