### ISSUE TITLE
Invalid stub output in `SENTIEON_DEDUP` crashes sentieon stub run

### ISSUE THREAD

**Issue by alkc** [nf-core/raredisease#462]
### Description of the bug

The stub files created by `SENTIEON_DEDUP` from nf-core/modules do not match that of the main process. 

This crashes raredisease when performing a stub run with `-profile test_sentieon` and params set in some `custom_profile` to:

```
aligner = 'sentieon'
variant_caller = 'sentieon'
```

In short, the stub run does not create bam/bai files when expected and lacks the `*.metrics.multiqc.tsv` output.

I've opened a pull request in nf-core/modules that should fix this issue: https://github.com/nf-core/modules/pull/4632

### Command used and terminal output

```console
$ nextflow run -stub -profile test_sentieon,singularity

ERROR ~ Error executing process > 'NFCORE_RAREDISEASE:RAREDISEASE:ALIGN:ALIGN_SENTIEON:SENTIEON_DEDUP (hugelymodelbat)'

Caused by:
  Missing output file(s) `*.bai` expected by process `NFCORE_RAREDISEASE:RAREDISEASE:ALIGN:ALIGN_SENTIEON:SENTIEON_DEDUP (hugelymodelbat)` (note: input files are not included in the
efault matching set)

Command executed:

  touch hugelymodelbat_dedup.cram
  touch hugelymodelbat_dedup.cram.crai
  touch hugelymodelbat_dedup.metrics
  touch hugelymodelbat_dedup.score

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RAREDISEASE:RAREDISEASE:ALIGN:ALIGN_SENTIEON:SENTIEON_DEDUP":
      sentieon: $(echo $(sentieon driver --version 2>&1) | sed -e "s/sentieon-genomics-//g")
  END_VERSIONS

Command exit status:
  0
```

### System information

Nextflow version 23.04.2
Container engine: Singularity
nf-core/raredisease dev branch
Executor slurm
HPC

**Comment by ramprasadn** [comment]
Closed this issue by mistake.. 4632 is pending 😅
