### ISSUE TITLE
Add option to take a whitelist of variants

### ISSUE THREAD

**Issue by jemten** [nf-core/raredisease#469]
### Description of feature

Right now we have the option of filtering the vcf to remove common mutations as they are very unlikely to cause a rare disease. However, some mutations are quite common and can still cause serious effects, one such example is founder mutations. It would be useful to be able to provide a vcf with variants that should never be filtered, i.e. a whitelist. These variants should then be rescued from the filtering happening here https://github.com/nf-core/raredisease/blob/c371602095ff83064f51747fe90dfc405ca7a864/subworkflows/local/annotate_snvs.nf#L79

**Comment by ramprasadn** [comment]
This is managed variants, right @jemten?

**Comment by jemten** [comment]
Exactly! Will close the issue since it has been implemented
