### ISSUE TITLE
Downsample MT alignment file for IGV

### ISSUE THREAD

**Issue by jemten** [nf-core/raredisease#497]
The mitochondria often gets very high coverage, making it difficult to view the alignments in IGV without it crashing. One solution is to downsample the mitochondria file to around 150x and save that file for manual inspection in IGV. The original alignment file will be used for variant calling. 

Ideas:
- Calculate original MT coverage and produce the fraction needed to downsample to 150x. use samtools view to dowsample to said fraction.
- It should be possible to always subsample a fixed number of reads if you know the input read length and chromosome length.

**Comment by ramprasadn** [comment]
Done!
