### ISSUE TITLE
Implementation of BWA

### ISSUE THREAD

**Issue by lfearnley** [nf-core/raredisease#519]
### Description of feature

Hi all! More an offer than a request - I've implemented BWA from nf-core's modules as an aligner option - I've been hitting segmentation faults when using BWA-MEM2, and ultimately it made more sense to drop back to BWA and match defaults for Sarek.

I'd like to contribute this back to the raredisease pipeline; are you open to pull requests from external authors?

**Comment by ramprasadn** [comment]
Hi @lfearnley! Thank you for the offer to contribute! We are always open to contributions from external authors. However, we have already added BWA as an aligner option in the rare disease pipeline in the dev branch so feel free to check it out. 
We appreciate your willingness to contribute and encourage you to keep an eye out for other issues where you can contribute. Thank you!

**Comment by lfearnley** [comment]
@ramprasadn - thanks; I've had a look at the dev branch but it's not really usable at present. I'm also running into significant problems getting nf-raredisease stably running, even with @fa2k's repo of settings and parameters.
