### ISSUE TITLE
URGENT: pin nf-validation version

### ISSUE THREAD

**Issue by nvnieuwk** [nf-core/raredisease#520]
### Description of the bug

To prevent breaking this pipeline in the near future, the nf-validation version should be pinned to version 1.1.3 like:

```
plugins {
    id 'nf-validation@1.1.3'
}
```

**Comment by jemten** [comment]
It's pinned in the dev branch and we're aiming to make a new release soon.
https://github.com/nf-core/raredisease/blob/071951a0627f5942e77a72afc3f52f0f9de36f8f/nextflow.config#L283

However, if this is already causing troubles we can look into doing a hotfix.

**Comment by nvnieuwk** [comment]
Thank you! This is not causing any issues for now but we would like to release nf-validation as soon as possible. (We just need to wait for all pipelines to pin their nf-validation version)
