### ISSUE TITLE
GATK4_GERMLINECNVCALLER modules don't emit .calls. Should be .cohortcalls or .casecalls?

### ISSUE THREAD

**Issue by bnjvrjnke** [nf-core/raredisease#535]
call_sv_germlinecnvcaller.nf use GATK4_GERMLINECNVCALLER.out.calls
https://github.com/nf-core/raredisease/blob/752a9e172d710c8c67bbb6791955c91eb6f5fbde/subworkflows/local/variant_calling/call_sv_germlinecnvcaller.nf#L43

GATK4_GERMLINECNVCALLER module only emit cohortcalls and casecalls
https://github.com/nf-core/raredisease/blob/752a9e172d710c8c67bbb6791955c91eb6f5fbde/modules/nf-core/gatk4/germlinecnvcaller/main.nf#L12

**Comment by jemten** [comment]
Thanks for reporting @bnjvrjnke. We'll make a patch for this

**Comment by ramprasadn** [comment]
This is now fixed in the latest release @bnjvrjnke.
