### ISSUE TITLE
ped file cannot be created when outdir is an s3 path

### ISSUE THREAD

**Issue by evanfloden** [nf-core/raredisease#554]
### Description of the bug

The ped file cannot be created when outdir is an s3 path, leading to an error.

For example, defining `--outdir s3:/rarediseases-workspace/results/` with the test data gives this error:

```
s3:/rarediseases-workspace/results/pipeline_info/justhusky.ped (No such file or directory)
```

I believe it is originating from this code, although the single s3:/ is also suspicious. 

```
// Function to generate a pedigree file
    public static File makePed(samples, outdir) {

        def case_name  = samples[0].case_id
        def outfile  = new File(outdir +"/pipeline_info/${case_name}" + '.ped')
        outfile.text = ['#family_id', 'sample_id', 'father', 'mother', 'sex', 'phenotype'].join('\t')
        def samples_list = []
        for(int i = 0; i<samples.size(); i++) {
            def sample_name =  samples[i].sample
            if (!samples_list.contains(sample_name)) {
                outfile.append('\n' + [samples[i].case_id, sample_name, samples[i].paternal, samples[i].maternal, samples[i].sex, samples[i].phenotype].join('\t'));
                samples_list.add(sample_name)
            }
        }
        return outfile
    }
```
    

### Command used and terminal output

```console
nextflow run 'https://github.com/nf-core/raredisease'
		 -name special_coulomb
		 --outdir 's3:/rarediseases-workspace/results/'
		 -r 2.0.1
		 -profile test
```

**Comment by ramprasadn** [comment]
Thank you, @evanfloden, for bringing this bug to our attention. You are correct!

We made some changes to the code last week, moving this functionality to a nextflow process rather than relying on groovy. Hopefully, this resolves the error. Please test our dev branch and inform us if the issue persists.

**Comment by ramprasadn** [comment]
Closing this issue as it was fixed in the last release. Feel free to reopen if needed.
