### ISSUE TITLE
destination filesystem does not support xattrs

### ISSUE THREAD

**Issue by hrydbeck** [nf-core/raredisease#565]
### Description of the bug

ERROR ~ Error executing process > 'NFCORE_RAREDISEASE:RAREDISEASE:CALL_MOBILE_ELEMENTS:RETROSEQ_DISCOVER (13)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name docker.io-clinicalgenomics-retroseq-1.5_9d4f3b5-1.img.pulling.1718117494807 docker://docker.io/clinicalgenomics/retroseq:1.5_9d4f3b5-1 > /dev/null
  status : 255
  message:
    INFO:    Converting OCI blobs to SIF format
    INFO:    Starting build...
    INFO:    Fetching OCI image...
    INFO:    Extracting OCI image...
    2024/06/11 16:51:47  warn xattr{var/cache/apt/archives/partial} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
    2024/06/11 16:51:47  warn xattr{/tmp/build-temp-1374007653/rootfs/var/cache/apt/archives/partial} destination filesystem does not support xattrs, further warnings will be suppressed
    FATAL:   While making image from oci registry: error fetching image to cache: while building SIF from layers: packer failed to pack: while unpacking tmpfs: error unpacking rootfs: unpack entry: opt/conda/pkgs/certifi-2019.9.11-py37_0/lib/python3.7/site-packages/certifi-2019.9.11-py3.7.egg-info/PKG-INFO: link: unpriv.link: unpriv.wrap target: no such file or directory

### Command used and terminal output

```console
nextflow run nf-core/raredisease -r "patch" -profile test,singularity,pdc_kth --outdir test_rev_patch_out --project naiss2024-22-481
```

### System information

Nextflow version 23.10.1
HPC,PDC-Dardel
slurm
Singularity
SUSE Linux Enterprise Server 15 SP5
nfc-rd version "patch"

**Comment by jemten** [comment]
related to #575 ?

**Comment by hrydbeck** [comment]
Yes, should this one then be closed?

**Comment by hrydbeck** [comment]
Closing
