### ISSUE TITLE
publishDir mode missing in raredisease.config for processes FASTQC and CREATE_PEDIGREE_FILE

### ISSUE THREAD

**Issue by irliampa** [nf-core/raredisease#583]
### Description of the bug

In conf/modules/raredisease.config, the mode of exporting the created files is missing for the FASTQC and CREATE_PEDIGREE_FILE processes, so no files are exported from the work directory to the results.
A warning is produced, thus the pipeline does not fail. In the respective work directories, the output files are created as expected. Troubleshooting of the .command files revealed an non informative "Operation not supported" error. It looked like symlinks were created, but since the mode was not specified, the file copying over to the results was not successful.

### Command used and terminal output

Partial terminal output:
```
WARN: Failed to publish file: /scratch/raredisease/363412/work/5d/5c3deb665f4db72abc13d9999f0ffe/50000010_T3_1_fastqc.html; to: /persistent/Eirini_Data_transfer/test_full_data/output_040424_A00001_0002_VFDB1B$
WARN: Failed to publish file: /scratch/raredisease/363412/work/5d/5c3deb665f4db72abc13d9999f0ffe/50000010_T3_2_fastqc.html; to: /persistent/Eirini_Data_transfer/test_full_data/output_040424_A00001_0002_VFDB1B$
WARN: Failed to publish file: /scratch/raredisease/363412/work/5d/5c3deb665f4db72abc13d9999f0ffe/50000010_T3_1_fastqc.zip; to: /persistent/Eirini_Data_transfer/test_full_data/output_040424_A00001_0002_VFDB1BG$
WARN: Failed to publish file: /scratch/raredisease/363412/work/5d/5c3deb665f4db72abc13d9999f0ffe/50000010_T3_2_fastqc.zip; to: /persistent/Eirini_Data_transfer/test_full_data/output_040424_A00001_0002_VFDB1BG$
```
```
WARN: Failed to publish file: /scratch/raredisease/363412/work/4f/1c98d207715d32f9464e825ea55442/50000009.ped; to: /persistent/Eirini_Data_transfer/test_full_data/output_040424_A00001_0002_VFDB1BGVCF/pedigree$
```

### System information

Nextflow version: 23.10.1
Hardware: HPC
Executor: slurm
Container engine: docker
OS: ubuntu 20.04
Version of nf-core/raredisease: 2.1.0

**Comment by ramprasadn** [comment]
Closing this as the relevant PR has been merged.
