### ISSUE TITLE
Allow 'lane' in samplesheet.csv to be String type (as in e.g. sarek)

### ISSUE THREAD

**Issue by sitems** [nf-core/raredisease#591]
### Description of feature

Hi, our fastq.gz data provider sequences one sample within multiple lanes and flowcells, and more than one sample can be present in one concrete flowcell+lane combination. For example, for 2 samples (D2077 and M245), pair end files look like this:

D2077_EKDN230048476-1A_H2W7MDSXC_L2_1.fq.gz   D2077_EKDN230048476-1A_H2W7MDSXC_L2_2.fq.gz
D2077_EKDN230048476-1A_HFJHGDSX7_L2_1.fq.gz   D2077_EKDN230048476-1A_HFJHGDSX7_L2_2.fq.gz
D2077_EKDN230048476-1A_HFTFWDSX7_L4_1.fq.gz   D2077_EKDN230048476-1A_HFTFWDSX7_L4_2.fq.gz
D2077_EKDN230048476-1A_HWTLVDSX7_L4_1.fq.gz  D2077_EKDN230048476-1A_HWTLVDSX7_L4_2.fq.gz

M245_EKDN230048452-1A_HFJHGDSX7_L2_1.fq.gz  MM245_EKDN230048452-1A_HFJHGDSX7_L2_2.fq.gz
MM245_EKDN230048452-1A_HFTFWDSX7_L4_1.fq.gz  MM245_EKDN230048452-1A_HFTFWDSX7_L4_2.fq.gz
MM245_EKDN230048452-1A_HWTLVDSX7_L4_1.fq.gz  MM245_EKDN230048452-1A_HWTLVDSX7_L4_2.fq.gz

So the same lane number can be present in multiple flowcells (flowcells in my example are H2W7MDSXC,HFJHGDSX7,HFTFWDSX7,HWTLVDSX7). How should I correctly specify the lane column in samplesheet.csv? In sarek, lane can be a string, so in my case, I would for example for the first pair use lane = H2W7MDSXC_L2.

**Comment by ramprasadn** [comment]
Thanks for reporting this @sitems! Sounds like a good idea. I will make a PR on this soon.

**Comment by ramprasadn** [comment]
This feature is now integrated into the raredisease project @sitems. Previously, lane information was not utilized for generating read groups, but I've now updated the code to include that functionality as well.

**Comment by ramprasadn** [comment]
I am closing this issue for now, but feel free to open it back up if needed.
