### ISSUE TITLE
Add default support for haploid variant calls

### ISSUE THREAD

**Issue by jemten** [nf-core/raredisease#596]
### Description of feature

Deepvariant version 1.6.1 has support for haploid calls on the X and Y chromosome for males, https://github.com/google/deepvariant/blob/r1.6.1/docs/deepvariant-haploid-support.md.

We could add the PAR region file as an optional input to be passed to the module and update the config for deepvariant to by default include the `--haploid_contigs` parameter for males. 

Could something like this:
```
        ext.args = { [
            "--model_type=${params.analysis_type.toUpperCase()}",
            (meta.sex == 1 ) ? ( (params.genome == 'GRCh37') ? '--haploid_contigs="X,Y"' : '--haploid_contigs="chrX,chrY"' ) ) : ''
        ].join(' ')}
```
I'm sure that there is a more elegant way of doing it 😆

**Comment by fellen31** [comment]
I forgot to add `--par_regions_bed` with the 1.6.1 module update, (added in https://github.com/nf-core/modules/pull/6022  yesterday), so the module in raredisease needs to be updated again.

**Comment by ramprasadn** [comment]
Added in https://github.com/nf-core/raredisease/pull/598
