### ISSUE TITLE
ERROR ~ while scanning a simple key

### ISSUE THREAD

**Issue by sitems** [nf-core/raredisease#603]
### Description of the bug

ERROR ~ while scanning a simple key                   
 in 'reader', line 3, column 1:
    0.4.8
    ^                                                                                                          
could not find expected ':' 
 in 'reader', line 4, column 1:
    
    ^

### Command used and terminal output

```console
nextflow run nf-core/raredisease -r 2.1.0 -profile docker -with-dag dag.dot -work-dir workdir -resume -config $HOME/sav/genetics/code/nextflow-raredisease.config --genome GRCh38 --analysis_type wes --platform illumina --save_reference --input $HOME/sav/genetics/code/test_samplesheet_raredisease_uno.csv --outdir output --target_bed $HOME/biocache/raredisease/kits/S07604514_hg38/S07604514_Covered.bed --bait_padding 500 --intervals_wgs $HOME/biocache/raredisease/raredisease-master/assets/chr1-chr22chrXchrYchrM_grch38.interval_list --intervals_y $HOME/biocache/raredisease/raredisease-master/assets/chrY_grch38.interval_list --variant_catalog $HOME/biocache/raredisease/reference-files-master/rare-disease/disease_loci/ExpansionHunter-v5.0.0/variant_catalog_grch38.json --rmdup --run_mt_for_wes --skip_snv_annotation --skip_vep_filter --skip_sv_annotation --skip_mt_annotation --skip_germlinecnvcaller --skip_me_calling --skip_me_annotation --aligner bwa
```

### System information

Nextflow version: 24.04.4.5917
Hardware: Desktop
Executor:local
Container engine: Docker
OS: Ubuntu 22.04
Version of nf-core/raredisease: 2.1.0

**Comment by ramprasadn** [comment]
I wasn’t able to replicate the issue on my end. If you have a .nextflow.log file, could you please share it with us? That would be really helpful. Thank you!

**Comment by ramprasadn** [comment]
Hi @sitems! Looks like this might coming from peddy. I am still not able to replicate this issue on our end, but that's the only tool with the version string "0.4.8". Could you share the versions.yml file in your peddy work directory? And the versions.yaml file in the multiqc directory?

**Comment by sitems** [comment]
Hi, unfortunately, I removed all the files, and switched to --skip_peddy option, but I can confirm, that when it failed, I saw the peddy tool as the last in the terminal, so it is very likely that the error came from peddy. Good news is that I switched to 2.2.0 release today, and it works. So we can close this issue now.

**Comment by ramprasadn** [comment]
Glad to know that it worked with the latest version @sitems. I will close this issue.
