### ISSUE TITLE
Create an interactive chart to use during pipeline development 

### ISSUE THREAD

**Issue by Gwennid** [nf-core/raredisease#61]
To complement the project board, we would like to have an interactive chart that can reflect the progresses of the development work and that can be easily modified e.g. when we want to include more tools.
nf-core recommends LucidChart or Google Drawings for such task. For the moment we are going for Google Drawings.

**Comment by projectoriented** [comment]
Cool! Could you share the Google Drawings link to here or on the raredisease slack channel?

**Comment by Gwennid** [comment]
First I need to ask all of your email addresses (linked to google) and change the edit permissions. Right now everyone with the link can edit, so I'm not sure it is a good idea to put it anywhere too "open".

**Comment by Gwennid** [comment]
Link to the [flowchart](https://docs.google.com/drawings/d/1QZsgxM4zuArI-N2kuWzwJB5PpjwOu8XxJ3-DInlNYEk/edit?usp=sharing).

**Comment by Gwennid** [comment]
<img src="https://docs.google.com/drawings/d/e/2PACX-1vTam7xjHBQTo1QsOpMUpd5F2vUZK5aXuf51OpSBaaV_2xMwfS1oN6GgVeQEJHjNNXRtCVHdGjCVFyzO/pub?w=2268&amp;h=2268">

**Comment by Gwennid** [comment]
I wrote "instructions" to update the flowchart, to help people to contribute. They are here: https://docs.google.com/document/d/1mPYi175FGNdD6YrvhSnbcmI7Qn6zwpyN656ogA_ZYRY/edit?usp=sharing
(the link has also been added to the flowchart page)
