### ISSUE TITLE
VEP 113

### ISSUE THREAD

**Issue by dnil** [nf-core/raredisease#640]
### Description of feature

Out now! 😸 

https://github.com/Ensembl/ensembl-vep/releases/tag/release%2F113.0
https://grch37.ensembl.org/info/docs/tools/vep/script/vep_download.html

Nice with CADD 1.7, gnomad 4.1 and interesting with the Parlogues plugin to somewhat selectively bring in variants from  paralogous regions. Thinking about that KRT6-family eg.

**Comment by jemten** [comment]
@ramprasadn has tested version 113 and found that certain BNDs are not annotated by VEP, https://github.com/Ensembl/ensembl-vep/issues/1774

**Comment by dnil** [comment]
Well spotted!

**Comment by ramprasadn** [comment]
VEP 113 is now integrated into our pipeline for those interested in utilizing it. 

However @dnil, it appears that BNDs overlapping intergenic variants are not being annotated by this version. The Ensembl team has acknowledged this issue and is actively investigating it. I hope they will resolve it in the next release. Given this bug, I don’t believe it is suitable for production use at CG at this time. I will close this issue for now. Please feel free to reopen it if necessary.
