### ISSUE TITLE
Germline or somatic

### ISSUE THREAD

**Issue by beginner984** [nf-core/raredisease#641]
Sorry, 

raredisease pipeline works for `germline` or `somatic` mutations? Can be used when there is no normal sample available (`tumour only mode`)?

Is any restriction for depth of coverage?

**Comment by ramprasadn** [comment]
Hi @beginner984! raredisease is developed for germline mutations. If you are keen on somatic mutations, I would suggest that you check out https://github.com/nf-core/sarek.

**Comment by ramprasadn** [comment]
Closing this issue for now, but feel free to reopen this if needed.
