### ISSUE TITLE
Check and create tbi index for bed inputs

### ISSUE THREAD

**Issue by ramprasadn** [nf-core/raredisease#67]
### Description of feature

Create a subworkflow to check if proper indices are available for bed files and create them when not.

**Comment by projectoriented** [comment]
What milestone is this part of?

**Comment by ramprasadn** [comment]
Manta has an option to take in a target bed file, that when I occurred to me that we need something similar to check vcf subworkflow, but for bed files. So I suppose this can be a part of structural variant calling milestone for now :)
