### ISSUE TITLE
Add Stranger to nf-core/modules

### ISSUE THREAD

**Issue by ljmesi** [nf-core/raredisease#90]
### Description of feature

https://github.com/Clinical-Genomics/stranger

**Comment by ljmesi** [comment]
It looks like Stranger is not available on bioconda yet. I wonder if this is a prerequisite for it to be included in nf-core/modules?

**Comment by jemten** [comment]
Doesn't have to be. But since it's on Pypi it should be fairly straight forward to get into conda. @ramprasadn maybe you can assist?

**Comment by ramprasadn** [comment]
@ljmesi They are flexible about letting tools that are not available on bioconda be on nf-core/modules.  As far as I know, they only let that happen in cases where having that tool on bioconda is made difficult for some reason (like missing dependencies etc.,). But like @jemten said, it should be relatively straightforward to write a bioconda recipe if the package is already on pypi. 

Check out the bioconda build command for pypi packages https://bioconda.github.io/contributor/guidelines.html#python. This should give you a template that you can then edit to build your own bioconda package. This process is very similar to adding a new module for nf-core. If you would like to take a look at a real world example of what your recipe file would look like, check out svdb recipe for bioconda (also built from a pypi package) here 
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/svdb/meta.yaml 

And of course, if you have any more questions or need help building the recipe do reach out to me either here or on slack :)

**Comment by ljmesi** [comment]
Thank you for your responses! I will check out the links you shared and start working on building a bioconda recipe first then.

**Comment by jemten** [comment]
This is done right @ljmesi?

**Comment by ljmesi** [comment]
Yes, it is. I'll close this issue.
